#!/usr/bin/env bash

source "$HOME/.config/colors.sh"
source "$HOME/.config/icons.sh"

PLUGIN_DIR="$HOME/.config/bottombar/plugins"
FONT="JetBrainsMono Nerd Font"

bottombar --bar color=0x00000000 height=40 margin=0 y_offset=3 padding_left=8 padding_right=8 sticky=on position=bottom topmost=window

bottombar --default padding_left=8 padding_right=5                    \
                     background.border_color=$COLOR_DEFAULT             \
                     background.border_width=2                         \
                     background.height=40                              \
                     background.corner_radius=12                       \
                     icon.color=$COLOR_DEFAULT                          \
                     icon.highlight_color=$COLOR_BACKGROUND            \
                     icon.padding_left=8 icon.padding_right=4          \
                     icon.font="$FONT:Regular:16.0"                    \
                     label.color=$COLOR_DEFAULT                         \
                     label.highlight_color=$COLOR_BACKGROUND           \
                     label.padding_left=4 label.padding_right=8        \
                     label.font="$FONT:Bold:12.0"

# === Left: Aerospace workspace indicator ===
bottombar --add item aerospace_mode left \
          --set aerospace_mode padding_left=3 padding_right=10 \
                               update_freq=1 \
                               script="$PLUGIN_DIR/aerospace.sh" \
                               click_script="$PLUGIN_DIR/aerospace_click.sh" \
          --subscribe aerospace_mode mouse.clicked

bottombar --add bracket aerospace aerospace_mode \
          --set aerospace background.color=$COLOR_BACKGROUND background.border_color=$COLOR_DEFAULT

bottombar --add item seperator.r1 left \
          --set seperator.r1 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

# === Left: Media ===
bottombar --add item appmedia left
bottombar --add item seperator.media left \
          --set seperator.media padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off
bottombar --add item media left \
          --set media script="$PLUGIN_DIR/media.sh" updates=on \
          --subscribe media media_change
bottombar --add item seperator.r2 left \
          --set seperator.r2 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

# === Right: Notifications ===
bottombar --add item notif right \
          --set notif icon.color=$COLOR_DEFAULT \
                      background.color=$COLOR_BACKGROUND \
                      icon=$ICON_NOTIF \
                      padding_left=6 padding_right=4 \
                      icon.padding_left=8 icon.padding_right=0 \
                      background.border_width=0 \
                      background.corner_radius=6 \
                      background.height=24 \
                      click_script="osascript -e 'tell application \"System Events\" to click menu bar item 1 of menu bar 1 of application process \"ControlCenter\"'"

bottombar --add bracket control notif \
          --set control background.color=$COLOR_BACKGROUND background.border_color=$COLOR_DEFAULT

bottombar --add item seperator.r3 right \
          --set seperator.r3 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

# === Right: Clock ===
bottombar --add item time right \
          --set time script="$PLUGIN_DIR/time.sh" \
                     update_freq=5 \
                     padding_left=2 padding_right=8 \
                     background.border_width=0 \
                     background.corner_radius=6 \
                     background.height=24 \
                     icon=$ICON_CLOCK

bottombar --add item date right \
          --set date script="$PLUGIN_DIR/date.sh" \
                     update_freq=60 \
                     padding_left=8 padding_right=2 \
                     background.height=24 \
                     icon=$ICON_CALENDAR

bottombar --add bracket clock time date \
          --set clock background.color=$COLOR_BACKGROUND background.border_color=$COLOR_DEFAULT

bottombar --add item seperator.r4 right \
          --set seperator.r4 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

# === Right: Process info ===
bottombar --add item appcount right \
          --set appcount script="$PLUGIN_DIR/app.sh" \
                         update_freq=5 \
                         padding_left=4 padding_right=8 \
                         background.border_width=0 \
                         background.corner_radius=6 \
                         background.height=24 \
                         icon=$ICON_PROCESS icon.highlight=on label.highlight=on

bottombar --add item conncount right \
          --set conncount script="$PLUGIN_DIR/connection.sh" \
                          update_freq=5 \
                          padding_left=8 padding_right=4 \
                          background.border_width=0 \
                          background.corner_radius=6 \
                          background.height=24 \
                          icon=$ICON_CONNECT icon.highlight=on label.highlight=on

bottombar --add bracket process appcount conncount \
          --set process background.color=$COLOR_BACKGROUND background.border_color=$COLOR_DEFAULT

bottombar --add item seperator.r5 right \
          --set seperator.r5 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

# === Right: System activity ===
bottombar --add item ram right \
          --set ram script="$PLUGIN_DIR/ram.sh" \
                    update_freq=5 \
                    padding_left=2 padding_right=8 \
                    background.border_width=0 \
                    background.corner_radius=6 \
                    background.height=24

bottombar --add item cpu right \
          --set cpu script="$PLUGIN_DIR/cpu.sh" \
                    update_freq=5 \
                    padding_left=4 padding_right=4 \
                    background.border_width=0 \
                    background.corner_radius=6 \
                    background.height=24

bottombar --add item disk right \
          --set disk script="$PLUGIN_DIR/disk.sh" \
                     update_freq=5 \
                     padding_left=8 padding_right=2 \
                     background.border_width=0 \
                     background.corner_radius=6 \
                     background.height=24

bottombar --add bracket activity ram cpu disk \
          --set activity background.color=$COLOR_BACKGROUND background.border_color=$COLOR_DEFAULT

bottombar --add item seperator.r6 right \
          --set seperator.r6 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

# === Right: Package updates ===
bottombar --add item brew right \
          --set brew icon="󰏓 " label=" 0" \
                     script="$PLUGIN_DIR/update.sh" \
                     background.corner_radius=6 \
                     update_freq=1000 \
                     padding_left=8 padding_right=8 \
                     background.border_width=0 \
                     background.height=24

bottombar --add bracket updates brew \
          --set updates background.color=$COLOR_BACKGROUND background.border_color=$COLOR_DEFAULT

bottombar --add item seperator.r7 right \
          --set seperator.r7 padding_left=4 padding_right=4 background.drawing=off icon.drawing=off label.drawing=off

bottombar --hotload true
bottombar --update
